### ISSUE TITLE
Hermex/WebUI: stale process after hermes update causes module version skew

### ISSUE THREAD

**Issue by ryetaylor406** [stephenschoettler/hermes-lcm#433]
### Problem

After upgrading Hermes Agent from v0.18 to v0.19, the Hermex WebUI (separate `~/hermes-webui/` process) failed to start new sessions with:

- `ImportError: cannot import name '_compression_warrants_another_preflight_pass' from 'agent.turn_context'`
- `TypeError: ContextCompressor.__init__() got an unexpected keyword argument 'model_thresholds'`
- Gateway log: `Context engine 'lcm' not found — falling back to built-in compressor`

Desktop and Telegram sessions worked fine.

### Root Cause

The WebUI is a **separate long-running process** from the gateway. After `hermes update`, the WebUI still had v0.18 Python modules cached in `sys.modules`. New on-disk files mixed with old cached ones at lazy-import time. Six attempted fixes (gateway restarts, symlinks, wrapper, core patch, bytecode clear, PWA cache clear) all failed because they targeted the wrong process.

### Fix

```bash
~/hermes-webui/ctl.sh restart
```

That was it. The WebUI process had been running 5 days 21 hours.

### Prevention

Added `WatchPaths` to the WebUI launchd plist to auto-restart when hermes-agent files change:

```xml
<key>WatchPaths</key>
<array>
    <string>/Users/rye/.hermes/hermes-agent/agent/agent_init.py</string>
    <string>/Users/rye/.hermes/hermes-agent/agent/context_compressor.py</string>
    <string>/Users/rye/.hermes/hermes-agent/agent/turn_context.py</string>
    <string>/Users/rye/.hermes/hermes-agent/agent/conversation_loop.py</string>
</array>
```

### Recommendation

Consider documenting: "After `hermes update`, restart the WebUI and the gateway." Or add a post-install hook. Longer-term: shipping `hermes-lcm` as a pip-installable package would eliminate the module-path/import issues that make this kind of version skew possible — plugins in `site-packages` survive agent updates cleanly.

### Environment

- macOS 26.3.1, Mac mini M4
- Hermes Agent v0.19.0 (upgraded from v0.18)
- hermes-lcm v0.19.0 (git cloned, main branch)
- WebUI at `~/hermes-webui/` on port 8787

Thanks for the plugin. The DAG summaries are excellent. Just want to help other Hermex users avoid the same debugging session.
